package:
  name: r-plotthis
  version: 0.3.4

source:
  git_url: https://github.com/pwwang/plotthis
  git_rev: 0.3.4

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - r-circlize
    - r-ggplot2
    - r-rlang
    - r-dplyr
    - r-tidyr
    - r-glue
    - r-forcats
    - r-gtable
    - r-reshape2
    - r-stringr
    - r-scales
    - r-patchwork
    - r-ggrepel
    - pwwang::r-gglogger
    - r-ggnewscale
    - r-cowplot
    - bioconda::bioconductor-complexheatmap
    - r-clustree
    - r-ggwordcloud
    - r-ggalluvial
    - r-ggvenndiagram
    - r-ggupset
    - r-ggpubr
    - r-ggforce
    - r-ggraph
    - r-ggridges
    - r-hexbin
    - r-igraph
    - r-scattermore
    - r-zoo
    - r-concaveman
    - r-inext

  run:
    - r-base
    - r-circlize
    - r-ggplot2
    - r-rlang
    - r-dplyr
    - r-tidyr
    - r-glue
    - r-forcats
    - r-gtable
    - r-reshape2
    - r-stringr
    - r-scales
    - r-patchwork
    - r-ggrepel
    - pwwang::r-gglogger
    - r-ggnewscale
    - r-cowplot
    - bioconda::bioconductor-complexheatmap
    - r-clustree
    - r-ggwordcloud
    - r-ggalluvial
    - r-ggvenndiagram
    - r-ggupset
    - r-ggpubr
    - r-ggforce
    - r-ggraph
    - r-ggridges
    - r-hexbin
    - r-igraph
    - r-scattermore
    - r-zoo
    - r-concaveman
    - r-inext

test:
  commands:
    - $R -e "library('plotthis')"

about:
  home: https://github.com/pwwang/plotthis
  license: GPL-3
  summary: plotthis is an R package that is built upon ggplot2 and other plotting packages.
  license_family: GPL
  license_file: LICENSE.md
